name: Sync Fork

on:
  schedule:
    - cron: '*/40 0 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: fanmingming
          base: master
          head: master
          repo: live
          merge_method : merge
          
